image: "redoxos/redoxer"

stages:
    - build
    - test

cache:
    paths:
        - target/

build:linux:
    stage: build
    script: cargo +nightly build --verbose

build:redox:
    stage: build
    script: redoxer build --verbose

test:linux:
    stage: test
    dependencies:
        - build:linux
    script: cargo +nightly test --verbose

test:redox:
    stage: test
    dependencies:
        - build:redox
    # do not test binaries, and detect if redoxer hangs
    script: redoxer test --verbose -- --test '*' --lib -- --nocapture
