workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAMESPACE == "redox-os"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

stages:
    - build
    - test

build:linux:
    stage: build
    script: cargo +nightly build --verbose

build:redox:
    stage: build
    script: redoxer build --verbose

test:linux:
    stage: test
    dependencies:
        - build:linux
    # Requires FUSE otherwise integ test can't be done
    script: ls /dev/fuse && cargo +nightly test --verbose

test:redox:
    stage: test
    dependencies:
        - build:redox
    # Requires KVM otherwise integ test will be super slow
    script: ls /dev/kvm && redoxer test
