workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAMESPACE == "redox-os"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

stages:
    - build
    - test

build:linux:
    stage: build
    script: cargo +nightly build

build:redox:
    stage: build
    script: redoxer build

test:linux:
    stage: test
    dependencies:
        - build:linux
    # TODO: fuse is racy?
    script: cargo +nightly test -- --test-threads=1

test:redox:
    stage: test
    dependencies:
        - build:redox
    # only run integration test as it's significantly slow even with KVM
    script: redoxer test --verbose -- --test '*' -- --nocapture
